package com.wv.timedtoggle.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskBeanDaoConfig;

    private final TaskBeanDao taskBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskBeanDaoConfig = daoConfigMap.get(TaskBeanDao.class).clone();
        taskBeanDaoConfig.initIdentityScope(type);

        taskBeanDao = new TaskBeanDao(taskBeanDaoConfig, this);

        registerDao(TaskBean.class, taskBeanDao);
    }
    
    public void clear() {
        taskBeanDaoConfig.getIdentityScope().clear();
    }

    public TaskBeanDao getTaskBeanDao() {
        return taskBeanDao;
    }

}
