package com.wv.timedtoggle.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK".
 */
public class Task {

    private Long id;
    /** Not-null value. */
    private String task;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String time;
    /** Not-null value. */
    private String enable;

    public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

    public Task(Long id, String task, String date, String time, String enable) {
        this.id = id;
        this.task = task;
        this.date = date;
        this.time = time;
        this.enable = enable;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTask() {
        return task;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTask(String task) {
        this.task = task;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getEnable() {
        return enable;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnable(String enable) {
        this.enable = enable;
    }

}
